# Generated by Django 3.2.9 on 2021-11-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fast_shipping',
            field=models.BooleanField(null=True),
        ),
    ]
